version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "3000:80" # Maps port 3000 to Nginx (port 80 in the container)
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "5000:5000" # Maps port 5000 to the backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
