version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
      args:
        REACT_APP_SOCKET_IO_URL: "${REACT_APP_SOCKET_IO_URL}"
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    env_file:
      - .env
    ports:
      - "3001:3001"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
